version: 2
jobs:
  test:
    docker:
      - image: python:2.7
    steps:
      - checkout
      - run: pip install pygame
      - run: python group_one_test.py

workflows:
  version: 2
  test:
    jobs:
      - test
